### ISSUE TITLE
How to remove slug /blog ?

### ISSUE THREAD

**Issue by tuanductran** [completejavascript/gatsby-blog-template#15]
Hello author, how to remove slug /blog

eg: from /blog/page/2 to /page/2

**Comment by completejavascript** [comment]
Technically, I add **/blog** slug to make it similar to **/tag/example-tag** and **/category/example-category** pattern.

It allow me to reuse the Pagination component.

So, if you want to remove the /blog, you need to update both **Create blog pages** section in gatsby-node.js and Pagination component by removing **pathPrefixBlog**.
