### ISSUE TITLE
Pagination bug at number 1

### ISSUE THREAD

**Issue by tuanductran** [completejavascript/gatsby-blog-template#16]
Hello author! at blog, cat and tag, how to remove number 1?

**Comment by completejavascript** [comment]
Can you give me a screenshot or steps to reproduce this issue?

The current slugs for the pagination are like: /blog, /blog/page/2, /blog/page/3....

The /blog/page/1 does not exist.

**Comment by tuanductran** [comment]
Done 😃 I used check if else pagination ===
