### ISSUE TITLE
Related Other Pages

### ISSUE THREAD

**Issue by mdestafadilah** [completejavascript/gatsby-blog-template#19]
Before i updated this template, i can refference my page to others page, but, now it's call twice the pages, any updated, where i must do thats?

**Comment by completejavascript** [comment]
Can you provide more details?

**Comment by mdestafadilah** [comment]
Yes.
this is my link -> https://topidesta.my.id/belajar/ .. its' pages, below .md style like here
```md
[Video](video)
```
it's same directory level between *belajar* and *video*, because it's page.

when i click video it's refference to -> https://topidesta.my.id/belajar/video not https://topidesta.my.id/video

thanks for you attention sir.

**Comment by completejavascript** [comment]
Change your markdown to be like this:

```
[Video](/video)
```

The `/` means the root domain.

Without the `/`, it become a sub-path from the current path.

**Comment by mdestafadilah** [comment]
Ok nice, its' work sir.

Thanks for your fast response.
