### ISSUE TITLE
Netlify CMS

### ISSUE THREAD

**Issue by mdestafadilah** [completejavascript/gatsby-blog-template#2]
Are you plan add netlify-cms as backend for creating content/post ?

**Comment by completejavascript** [comment]
I also wanted to add netlify CMS as backend for creating post. But it is complicated.

On the other hand, I just make a basic template. So you are easier to customize it whenever you want.

Anyway, do you have any experiences with Netlify CMS? @mdestafadilah

**Comment by mdestafadilah** [comment]
I have no any experiences, sorry. i'm just player, i'm using Gatsby because lack of ads(too many ads) in wordpress.com, for my writing something in blog, in free version.
