### ISSUE TITLE
Can't add more icons

### ISSUE THREAD

**Issue by pandevim** [completejavascript/gatsby-blog-template#4]
Not able to use other icons from fontawesome in`SiteConfig.js` file. The below config does not work.
```js
  socialLinks: [
    { 
      label: "Instagram", 
      url: "https://www.instagram.com/", 
      iconClassName: "fab instagram"
    }
  ],
```
Where are you initializing all the icons?

**Comment by completejavascript** [comment]
You can check this file to add more icon:

https://github.com/completejavascript/gatsby-blog-template/blob/dev/src/components/Icons/FontAwesome.jsx
